print("quien ganara, keiko o jp")
print("ya casi termina el semestre")
print("ya casi se acaban las clases")
print("ya casi se acaban las tareas")   
print("ya casi se acaban los proyectos")    
print("ya casi se acaban los examenes")
print("ya casi se acaban las presentaciones")
print("ya casi se acaban las actividades")
print("ya casi se acaban las responsabilidades")
print("ya casi se acaban las obligaciones")
print("ya casi se acaban las preocupaciones")